### ISSUE TITLE
KeyError and ValueError Encountered While Running Quickstart Example in Python 3.8 and 3.10 Environments

### ISSUE THREAD

**Issue by salujajustin** [project-lighter/lighter#119]
## 🐛 Bug Report

When trying to reproduce the Quickstart example using `pip install project-lighter` and `pip install project-lighter --pre`, I encountered two errors. Both Python 3.8 and 3.10 environments return identical errors. Without the `--pre` option specified there is a `ValueError: run ID 'run' doesn't exist in the config file.` and with the `--pre` option there is a `KeyError: "id='trainer' is not found in the config resolver."`. See the attached screenshots for more details. 

## 🔬 How To Reproduce

1. Start with a fresh python 3.8 or 3.10 install in a virtual environment
2. Install the package with `pip install project-lighter` or `pip install project-lighter --pre`.
3. Create a `cifar10.yaml` config with the provided content.
4. Run the command `lighter fit --config_file cifar10.yaml`.

### Code sample

Step 1:
```bash
micromamba create -n ssl-thymus-lighter  
micromamba activate ssl-thymus-lighter
micromamba install python=3.8 -c conda-forge
```

Step 2:
```bash
pip install project-lighter
```
or:
```bash
pip install project-lighter --pre
```

Step 3:
```yaml
system:
  _target_: lighter.LighterSystem
  batch_size: 512

  model:
    _target_: torchvision.models.resnet18
    num_classes: 10

  criterion:
    _target_: torch.nn.CrossEntropyLoss

  optimizer:
    _target_: torch.optim.Adam
    params: "$@system#model.parameters()"
    lr: 0.001

  datasets:
    train:
      _target_: torchvision.datasets.CIFAR10
      download: True
      root: .datasets
      train: True
      transform:
        _target_: torchvision.transforms.Compose
        transforms:
          - _target_: torchvision.transforms.ToTensor
          - _target_: torchvision.transforms.Normalize
            mean: [0.5, 0.5, 0.5]
            std: [0.5, 0.5, 0.5]
```

Step 4:
```bash
lighter fit --config_file cifar10.yaml
```

### Environment

* OS: Linux 5.15.0-105-generic 20.04.1-Ubuntu
* Venv: micromamba with conda
* Python version: 3.8 and 3.10

### Screenshots

The following is the output for the lighter package from  `pip install project-lighter`:
![image](https://github.com/project-lighter/lighter/assets/15842140/d38c78c6-b8b5-4108-a782-cd879df7bbc6)

The following is the output for the lighter package from `pip install project-lighter --pre`:
![image](https://github.com/project-lighter/lighter/assets/15842140/d7217a21-ef12-487b-8b2c-c2a973efb57f)

## 📈 Expected behavior

The training should start without any errors when running `lighter fit --config_file cifar10.yaml`

## 📎 Additional context
 
None.
