### ISSUE TITLE
Composable config

### ISSUE THREAD

**Issue by ibro45** [project-lighter/lighter#5]
Add a resolver that allows loading that part of the configuration from another yaml file.

For example:
```
train_dataset:
        _target_: torchvision.datasets.CIFAR10
        download: True
        root: ./.datasets/
        train: True
        transform: ${load_yaml: <YAML_PATH>}  # This line
```

Is it a good idea?
