### ISSUE TITLE
Passing Trainer/Tuner method's (`fit`, `predict`) arguments through YAML or CLI

### ISSUE THREAD

**Issue by ibro45** [project-lighter/lighter#99]
If we allow only a certain root level config entries such as `trainer`, `system`, and whatever we end up calling `CONSTANTS`, we could also reserve the following: `fit`, `predict`, `validate`, `test`, `tune`, `lr_find`, and `scale_batch_size` (the last two are from `Tuner`). These would be passed directly to their respective argument when run.

Then either through CLI or YAML we could specify for example

`lighter fit --config_file continue.yaml --fit#ckpt_path="./trained.ckpt"`

```yaml
fit#ckpt_path: trained.ckpt
# or
fit:
    ckpt_path: trained.ckpt
```
